# Generated by Django 2.1.4 on 2019-01-07 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('age_rating', models.IntegerField(choices=[[1, '0+'], [2, '6+'], [3, '12+'], [4, '16+'], [5, '18+']], default=5)),
                ('paid', models.BooleanField(default=0)),
                ('price', models.PositiveSmallIntegerField()),
                ('description', models.TextField(max_length=9999)),
                ('mainPhoto', models.FileField(upload_to='events /mainPhotos /%Y/%m/%d/')),
                ('morePhotos', models.FileField(upload_to='events /morePhotos /%Y/%m/%d/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
