# Generated by Django 2.1.4 on 2019-01-07 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_event', '0002_event_hashtags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='hashtags',
        ),
    ]
