# Generated by Django 2.1.5 on 2019-01-07 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_event', '0004_event_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tags',
        ),
    ]
