# Generated by Django 2.1.5 on 2019-01-07 13:26

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('create_event', '0005_remove_event_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hashtags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
